/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "work.h"

bool_t
xdr_work(xdrs, objp)
	XDR *xdrs;
	work *objp;
{
	int32_t *buf;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, (1 + 32 + 8) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->data, 32, sizeof(int), (xdrproc_t)xdr_int))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->target, 8, sizeof(int), (xdrproc_t)xdr_int))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->height))
				return (FALSE);
		} else {
			{
				int i;
				int *genp;

				for (i = 0, genp = objp->data;
				    i < 32; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			{
				int i;
				int *genp;

				for (i = 0, genp = objp->target;
				    i < 8; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
			IXDR_PUT_LONG(buf, objp->height);
		}
		if (!xdr_pointer(xdrs, (char **)&objp->txs, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->workid, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->job_id, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->xnonce2_len))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->xnonce2, sizeof(u_char), (xdrproc_t)xdr_u_char))
			return (FALSE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, (1 + 32 + 8) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_vector(xdrs, (char *)objp->data, 32, sizeof(int), (xdrproc_t)xdr_int))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->target, 8, sizeof(int), (xdrproc_t)xdr_int))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->height))
				return (FALSE);
		} else {
			{
				int i;
				int *genp;

				for (i = 0, genp = objp->data;
				    i < 32; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			{
				int i;
				int *genp;

				for (i = 0, genp = objp->target;
				    i < 8; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
			objp->height = IXDR_GET_LONG(buf);
		}
		if (!xdr_pointer(xdrs, (char **)&objp->txs, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->workid, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->job_id, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->xnonce2_len))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->xnonce2, sizeof(u_char), (xdrproc_t)xdr_u_char))
			return (FALSE);
	} else {
		if (!xdr_vector(xdrs, (char *)objp->data, 32, sizeof(int), (xdrproc_t)xdr_int))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->target, 8, sizeof(int), (xdrproc_t)xdr_int))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->height))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->txs, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->workid, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->job_id, sizeof(char), (xdrproc_t)xdr_char))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->xnonce2_len))
			return (FALSE);
		if (!xdr_pointer(xdrs, (char **)&objp->xnonce2, sizeof(u_char), (xdrproc_t)xdr_u_char))
			return (FALSE);
	}
	return (TRUE);
}
