/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _WORK_H_RPCGEN
#define _WORK_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct work {
	int data[32];
	int target[8];
	int height;
	char *txs;
	char *workid;
	char *job_id;
	int xnonce2_len;
	u_char *xnonce2;
};
typedef struct work work;
#ifdef __cplusplus
extern "C" bool_t xdr_work(XDR *, work*);
#elif __STDC__
extern  bool_t xdr_work(XDR *, work*);
#else /* Old Style C */
bool_t xdr_work();
#endif /* Old Style C */


#endif /* !_WORK_H_RPCGEN */
